// Downloads the official Ko-fi widget PNG and embeds it as a base64 data URL
// in `src/kofi-asset.ts`. Wired as a prebuild hook so the asset is regenerated
// alongside the icons. Idempotent - skips the fetch when the generated file
// already exists.
//
// We bake the image into the bundle (rather than loading it from
// storage.ko-fi.com at runtime) because Strava's content-script CSP blocks
// third-party `img-src`, and because a data URL keeps the extension working
// fully offline.

import { stat, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(here, '..');
const src = 'https://storage.ko-fi.com/cdn/kofi6.png?v=6';
const dst = path.join(root, 'src', 'kofi-asset.ts');

try {
	await stat(dst);
	console.log('kofi-asset.ts already present - skipping (delete to refetch).');
	process.exit(0);
} catch {
	/* fall through to download */
}

console.log(`fetching ${src} ...`);
const res = await fetch(src);
if (!res.ok) {
	console.error(`Ko-fi asset fetch failed: HTTP ${res.status}`);
	process.exit(1);
}
const bytes = Buffer.from(await res.arrayBuffer());
const dataUrl = `data:image/png;base64,${bytes.toString('base64')}`;
const contents =
	'// Auto-generated by scripts/build-kofi.js. Do not edit.\n' +
	`export const KOFI_IMAGE: string = ${JSON.stringify(dataUrl)};\n`;
await writeFile(dst, contents);
console.log(`wrote ${dst} (${bytes.length} bytes → ${dataUrl.length} char data URL)`);
